# Generated by Django 3.2.5 on 2021-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='prior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='related',
            field=models.ManyToManyField(related_name='_tag_tag_related_+', to='tag.Tag'),
        ),
    ]
