# Generated by Django 3.2.6 on 2021-11-05 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_picture', models.URLField()),
                ('description', models.CharField(max_length=1000)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('link', models.URLField()),
                ('completion', models.BooleanField()),
                ('score_sum', models.FloatField(default=0)),
                ('review_num', models.IntegerField(default=0)),
                ('platform_id', models.IntegerField(choices=[(1, 'Naver'), (2, 'Kakao'), (3, 'Lezhin')])),
                ('artists', models.ManyToManyField(related_name='works', to='artist.Artist')),
                ('tags', models.ManyToManyField(related_name='works', to='tag.Tag')),
            ],
        ),
    ]
