# Generated by Django 3.2.8 on 2021-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='platform_id',
            field=models.IntegerField(choices=[(1, 'Naver'), (2, 'Kakao'), (3, 'Lezhin')]),
        ),
    ]
