# Generated by Django 3.2.8 on 2021-11-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='work.work'),
        ),
    ]
