# Generated by Django 3.2.8 on 2021-11-06 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_alter_review_work_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='work_id',
            new_name='work',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.customuser'),
            preserve_default=False,
        ),
    ]
